name: Send News Email

on:
  schedule:
    - cron: '47 18 * * *' # Runs at 20:47 CEST (18:47 UTC) every day
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the email script
      run: python main.py
      env:
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        RECIPIENT_EMAILS: ${{ secrets.RECIPIENT_EMAILS }}
